[package]
name = "day_01_trebuchet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aho-corasick = "1.1.2"

[[bin]]
name = "main"
path = "main.rs"
